# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/Shopify/ejson
%global goipath         github.com/Shopify/ejson
Version:                1.3.3

%gometa -f

%global goname ejson

%global common_description %{expand:
EJSON is a small library to manage encrypted secrets using asymmetric
encryption.}

%global golicenses      LICENSE.txt
%global godocs          CONTRIBUTING.md CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        EJSON is a small library to manage encrypted secrets using asymmetric encryption

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/%{name} %{goipath}/cmd/%{name}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc CONTRIBUTING.md CHANGELOG.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
