# Generated by go2rpm 1.6.0
# Needs network
%bcond_with check
%global debug_package %{nil}

# https://github.com/google/go-github
%global goipath         github.com/google/go-github
Version:                51.0.0

%gometa

%global goaltipaths     github.com/google/go-github/v51

%global common_description %{expand:
Package Github provides a client for using the GitHub API.}

%global golicenses      LICENSE
%global godocs          AUTHORS CONTRIBUTING.md README.md

Name:           golang-github-google-go-github
Release:        %autorelease
Summary:        Go library for accessing the GitHub API

License:        BSD-3-Clause
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf example

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
